### PR TITLE
feat(everything): redesign, add blog

### PR DESCRIPTION
**Pull request by ghost**
* move to bootstrap. i found fomantic UI's documentation very frustrating to work with!
* redesign.
* add blog with the "introduction to wobbly" article and "convocational development" article. (both slightly edited)
* add link to contact us.

preview: https://redesign.wobbly.app/

### CODE REVIEW

**Comment by King-Mob** [comment]
I got this error on clicking on redesign.wobbly.app -> redesign.wobbly.app normally uses encryption to protect your information. When Google Chrome tried to connect to redesign.wobbly.app this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be redesign.wobbly.app, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Google Chrome stopped the connection before any data was exchanged.

You cannot visit redesign.wobbly.app right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later.

**Comment by ghost** [comment]
okay, looks like github pages will take some time to set up SSL. give it up to 24 hours :)

— Tao

**Comment by ghost** [comment]
@King-Mob i added a contact us link and a fancier splash image to https://redesign.wobbly.app:

Screenshot_2019-04-23 Wobbly 21st century workers' power

**Comment by ghost** [comment]
merging as per agreement with @King-Mob on discord

**Comment by ghost** [comment]
merging in #14.

**Pull request closed without merging**
